# AUTHOR           : Chris Benosa
# DATE             : 28/12/2021
# IMPORTANT NOTE   : "Please do not change anything to this file.  c/o author"

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing serverless and dependencies"
      - ASSUME_ROLE_ARN=${DEPLOY_ROLE}
      - echo $ASSUME_ROLE_ARN
      - aws sts get-caller-identity
      - TEMP_ROLE=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name serverless-api)
      - export AWS_ACCESS_KEY_ID=$(echo $TEMP_ROLE | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_ROLE | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $TEMP_ROLE | jq -r '.Credentials.SessionToken')
      - export AWS_ACCESS_PROFILE="TEMP_AWS_PROFILE"
      - npm install -g serverless@3.38.0 --unsafe && npm install --omit=dev
      - mkdir -p ~/.aws
      - echo "[$AWS_ACCESS_PROFILE]" > ~/.aws/credentials
      - echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      - echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
      - echo "aws_session_token=${AWS_SESSION_TOKEN}" >> ~/.aws/credentials
  pre_build:
    commands:
      - PARAM_PREFIX="/${SERVICE_NAME}/${STAGE}"
      - echo $PARAM_PREFIX
      - PARAMETER="env"
      - PARAM_KEY="$PARAM_PREFIX/$PARAMETER"
      - echo $PARAM_KEY
      - DEST_FILENAME="herpderp.${STAGE}"
      - aws ssm get-parameter --name $PARAM_KEY --region $REGION --output text --query Parameter.Value > $DEST_FILENAME
      - export $(grep -v '^#' $DEST_FILENAME | xargs -d '\n')
      - echo $DEST_FILENAME
  build:
    commands:
      - serverless deploy --stage $STAGE --aws-profile $AWS_ACCESS_PROFILE --region $REGION --config serverless.yml
  post_build:
    commands:
      - npm install aws-sdk
      # - npm run dynamo:migrate
