# AUTHOR           : Chris Benosa
# DATE             : 28/12/2021
# IMPORTANT NOTE   : "Please do not change anything to this file.  c/o author"

version: 0.2
run-as: root
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ASSUME_ROLE_ARN=${DEPLOY_ROLE}
      - echo $ASSUME_ROLE_ARN
      - aws sts get-caller-identity 
      - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name brad-sls-api` 
      - export TEMP_ROLE 
      # - echo $TEMP_ROLE
      # - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name brad_deployer`
      - export TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - export AWS_ACCESS_PROFILE="TEMP_AWS_PROFILE"
      # - mkdir ~/.npm-global
      # - npm config set prefix '~/.npm-global'
      - npm install -g serverless@2.43.1 --unsafe && npm install --production
      - AWS_CREDENTIAL_FILE=~/.aws/credentials
      - mkdir ~/.aws
      - touch $AWS_CREDENTIAL_FILE
      - chmod 600 $AWS_CREDENTIAL_FILE
      - echo "["$AWS_ACCESS_PROFILE"]" > $AWS_CREDENTIAL_FILE
      - echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> $AWS_CREDENTIAL_FILE
      - echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> $AWS_CREDENTIAL_FILE
      - echo "aws_session_token=${AWS_SESSION_TOKEN}" >> $AWS_CREDENTIAL_FILE
  pre_build:
    commands:
      # - SERVICE_NAME="BRAD_API"
      # - npm update
      - PARAM_PREFIX="/${SERVICE_NAME}/${STAGE}"
      - echo $PARAM_PREFIX
      - PARAMETER="env"
      - PARAM_KEY="$PARAM_PREFIX/$PARAMETER"
      - echo $PARAM_KEY
      - DEST_FILENAME="herpderp.${STAGE}"
      - aws ssm get-parameter --name $PARAM_KEY --region $REGION --output text --query Parameter.Value > $DEST_FILENAME
      - export $(grep -v '^#' $DEST_FILENAME | xargs -d '\n')
      - echo $DEST_FILENAME
  build:
    commands:
      - serverless deploy --stage $STAGE --aws-profile $AWS_ACCESS_PROFILE --region $REGION --config serverless-corpo.yml
      - serverless deploy --stage $STAGE --aws-profile $AWS_ACCESS_PROFILE --region $REGION --config serverless-admin.yml
  post_build:
    commands:
      - npm install aws-sdk
      # - npm run dynamo:migrate