/* tslint:disable */
/* eslint-disable */
/**
 * Datafied Chase API
 * API that workflow and Portals use to integrate to Order Repository Chase instances
 *
 * OpenAPI spec version: 1.0.2-A2
 * Contact: L.Jeganathan@leonardo.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * To be returned as part of a chase search result using /grouped-chases API
 *
 * @export
 * @interface GroupedChasesExcerpt
 */
export interface GroupedChasesExcerpt {

    /**
     * Practitioners TIN number
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example 10579845
     */
    tin?: string;

    /**
     * Practitioners Id
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example 539892
     */
    doctorId?: string;

    /**
     * facility name
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example DR HY P NGO MD
     */
    facility?: string;

    /**
     * Provider Id
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example 1323471
     */
    providerId?: string;

    /**
     * Provider name
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example DR HY P NGO MD
     */
    providerName?: string;

    /**
     * Project Id
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example 2903e393-7994-42c2-9581-261d6aec52a0
     */
    projectId?: string;

    /**
     * Project Name
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example testtenanta
     */
    projectName?: string;

    /**
     * organization Unit Name
     *
     * @type {string}
     * @memberof GroupedChasesExcerpt
     * @example Audit Test Client
     */
    orgUnitName?: string;

    /**
     * numbers of document by grouped chases
     *
     * @type {number}
     * @memberof GroupedChasesExcerpt
     * @example 1
     */
    docCount?: number;
}
